version: '2'
services:
    couch:
        image: couchdb
        container_name: couch
        ports:
            - 5984:5984
        expose:
            - 5984

    mazeapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: mazeapi
        depends_on:
            - couch
        links:
            - couch
        ports:
            - 80:80
            - 7698:80
        expose:
            - 80
